import os
os.system("cls")

# built-in exception
print("Built in exception")